import Head from "next/head";
import ProductGrid from "../components/ProductGrid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Simple Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen bg-slate-100">
        <div className="max-w-7xl mx-auto py-8">
          <h1>Welcome</h1>
          <div className="my-8">
            <ProductGrid />
          </div>
        </div>
      </main>
    </div>
  );
}
